// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotionSensorService.proto

package com.ncirl.smartwarehouse;

/**
 * <pre>
 * Request message to send motion detection status
 * </pre>
 *
 * Protobuf type {@code com.ncirl.smartwarehouse.DetectMotionStatusRequest}
 */
public  final class DetectMotionStatusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ncirl.smartwarehouse.DetectMotionStatusRequest)
    DetectMotionStatusRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DetectMotionStatusRequest.newBuilder() to construct.
  private DetectMotionStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DetectMotionStatusRequest() {
    isMotionDetected_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DetectMotionStatusRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isMotionDetected_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ncirl.smartwarehouse.MotionSensorServiceProto.internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ncirl.smartwarehouse.MotionSensorServiceProto.internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ncirl.smartwarehouse.DetectMotionStatusRequest.class, com.ncirl.smartwarehouse.DetectMotionStatusRequest.Builder.class);
  }

  public static final int ISMOTIONDETECTED_FIELD_NUMBER = 1;
  private boolean isMotionDetected_;
  /**
   * <code>bool isMotionDetected = 1;</code>
   */
  public boolean getIsMotionDetected() {
    return isMotionDetected_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isMotionDetected_ != false) {
      output.writeBool(1, isMotionDetected_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isMotionDetected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isMotionDetected_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ncirl.smartwarehouse.DetectMotionStatusRequest)) {
      return super.equals(obj);
    }
    com.ncirl.smartwarehouse.DetectMotionStatusRequest other = (com.ncirl.smartwarehouse.DetectMotionStatusRequest) obj;

    boolean result = true;
    result = result && (getIsMotionDetected()
        == other.getIsMotionDetected());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISMOTIONDETECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsMotionDetected());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ncirl.smartwarehouse.DetectMotionStatusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message to send motion detection status
   * </pre>
   *
   * Protobuf type {@code com.ncirl.smartwarehouse.DetectMotionStatusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ncirl.smartwarehouse.DetectMotionStatusRequest)
      com.ncirl.smartwarehouse.DetectMotionStatusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ncirl.smartwarehouse.MotionSensorServiceProto.internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ncirl.smartwarehouse.MotionSensorServiceProto.internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ncirl.smartwarehouse.DetectMotionStatusRequest.class, com.ncirl.smartwarehouse.DetectMotionStatusRequest.Builder.class);
    }

    // Construct using com.ncirl.smartwarehouse.DetectMotionStatusRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isMotionDetected_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ncirl.smartwarehouse.MotionSensorServiceProto.internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_descriptor;
    }

    @java.lang.Override
    public com.ncirl.smartwarehouse.DetectMotionStatusRequest getDefaultInstanceForType() {
      return com.ncirl.smartwarehouse.DetectMotionStatusRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ncirl.smartwarehouse.DetectMotionStatusRequest build() {
      com.ncirl.smartwarehouse.DetectMotionStatusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ncirl.smartwarehouse.DetectMotionStatusRequest buildPartial() {
      com.ncirl.smartwarehouse.DetectMotionStatusRequest result = new com.ncirl.smartwarehouse.DetectMotionStatusRequest(this);
      result.isMotionDetected_ = isMotionDetected_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ncirl.smartwarehouse.DetectMotionStatusRequest) {
        return mergeFrom((com.ncirl.smartwarehouse.DetectMotionStatusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ncirl.smartwarehouse.DetectMotionStatusRequest other) {
      if (other == com.ncirl.smartwarehouse.DetectMotionStatusRequest.getDefaultInstance()) return this;
      if (other.getIsMotionDetected() != false) {
        setIsMotionDetected(other.getIsMotionDetected());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ncirl.smartwarehouse.DetectMotionStatusRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ncirl.smartwarehouse.DetectMotionStatusRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isMotionDetected_ ;
    /**
     * <code>bool isMotionDetected = 1;</code>
     */
    public boolean getIsMotionDetected() {
      return isMotionDetected_;
    }
    /**
     * <code>bool isMotionDetected = 1;</code>
     */
    public Builder setIsMotionDetected(boolean value) {
      
      isMotionDetected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isMotionDetected = 1;</code>
     */
    public Builder clearIsMotionDetected() {
      
      isMotionDetected_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ncirl.smartwarehouse.DetectMotionStatusRequest)
  }

  // @@protoc_insertion_point(class_scope:com.ncirl.smartwarehouse.DetectMotionStatusRequest)
  private static final com.ncirl.smartwarehouse.DetectMotionStatusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ncirl.smartwarehouse.DetectMotionStatusRequest();
  }

  public static com.ncirl.smartwarehouse.DetectMotionStatusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DetectMotionStatusRequest>
      PARSER = new com.google.protobuf.AbstractParser<DetectMotionStatusRequest>() {
    @java.lang.Override
    public DetectMotionStatusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DetectMotionStatusRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DetectMotionStatusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DetectMotionStatusRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ncirl.smartwarehouse.DetectMotionStatusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

