// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotionSensorService.proto

package com.ncirl.smartwarehouse;

public interface DetectMotionStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.smartwarehouse.DetectMotionStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isMotionDetected = 1;</code>
   */
  boolean getIsMotionDetected();
}
