// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotionSensorService.proto

package com.ncirl.smartwarehouse;

public interface DetectMotionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.smartwarehouse.DetectMotionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
