// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightSensorService.proto

package com.ncirl.smartwarehouse;

/**
 * Protobuf type {@code com.ncirl.smartwarehouse.LightResponse}
 */
public  final class LightResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ncirl.smartwarehouse.LightResponse)
    LightResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LightResponse.newBuilder() to construct.
  private LightResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LightResponse() {
    increaseBrightness_ = false;
    decreaseBrightness_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LightResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            increaseBrightness_ = input.readBool();
            break;
          }
          case 16: {

            decreaseBrightness_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ncirl.smartwarehouse.LightSensorServiceProto.internal_static_com_ncirl_smartwarehouse_LightResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ncirl.smartwarehouse.LightSensorServiceProto.internal_static_com_ncirl_smartwarehouse_LightResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ncirl.smartwarehouse.LightResponse.class, com.ncirl.smartwarehouse.LightResponse.Builder.class);
  }

  public static final int INCREASEBRIGHTNESS_FIELD_NUMBER = 1;
  private boolean increaseBrightness_;
  /**
   * <code>bool increaseBrightness = 1;</code>
   */
  public boolean getIncreaseBrightness() {
    return increaseBrightness_;
  }

  public static final int DECREASEBRIGHTNESS_FIELD_NUMBER = 2;
  private boolean decreaseBrightness_;
  /**
   * <code>bool decreaseBrightness = 2;</code>
   */
  public boolean getDecreaseBrightness() {
    return decreaseBrightness_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (increaseBrightness_ != false) {
      output.writeBool(1, increaseBrightness_);
    }
    if (decreaseBrightness_ != false) {
      output.writeBool(2, decreaseBrightness_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (increaseBrightness_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, increaseBrightness_);
    }
    if (decreaseBrightness_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, decreaseBrightness_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ncirl.smartwarehouse.LightResponse)) {
      return super.equals(obj);
    }
    com.ncirl.smartwarehouse.LightResponse other = (com.ncirl.smartwarehouse.LightResponse) obj;

    boolean result = true;
    result = result && (getIncreaseBrightness()
        == other.getIncreaseBrightness());
    result = result && (getDecreaseBrightness()
        == other.getDecreaseBrightness());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INCREASEBRIGHTNESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncreaseBrightness());
    hash = (37 * hash) + DECREASEBRIGHTNESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDecreaseBrightness());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ncirl.smartwarehouse.LightResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ncirl.smartwarehouse.LightResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ncirl.smartwarehouse.LightResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ncirl.smartwarehouse.LightResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ncirl.smartwarehouse.LightResponse)
      com.ncirl.smartwarehouse.LightResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ncirl.smartwarehouse.LightSensorServiceProto.internal_static_com_ncirl_smartwarehouse_LightResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ncirl.smartwarehouse.LightSensorServiceProto.internal_static_com_ncirl_smartwarehouse_LightResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ncirl.smartwarehouse.LightResponse.class, com.ncirl.smartwarehouse.LightResponse.Builder.class);
    }

    // Construct using com.ncirl.smartwarehouse.LightResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      increaseBrightness_ = false;

      decreaseBrightness_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ncirl.smartwarehouse.LightSensorServiceProto.internal_static_com_ncirl_smartwarehouse_LightResponse_descriptor;
    }

    @java.lang.Override
    public com.ncirl.smartwarehouse.LightResponse getDefaultInstanceForType() {
      return com.ncirl.smartwarehouse.LightResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ncirl.smartwarehouse.LightResponse build() {
      com.ncirl.smartwarehouse.LightResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ncirl.smartwarehouse.LightResponse buildPartial() {
      com.ncirl.smartwarehouse.LightResponse result = new com.ncirl.smartwarehouse.LightResponse(this);
      result.increaseBrightness_ = increaseBrightness_;
      result.decreaseBrightness_ = decreaseBrightness_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ncirl.smartwarehouse.LightResponse) {
        return mergeFrom((com.ncirl.smartwarehouse.LightResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ncirl.smartwarehouse.LightResponse other) {
      if (other == com.ncirl.smartwarehouse.LightResponse.getDefaultInstance()) return this;
      if (other.getIncreaseBrightness() != false) {
        setIncreaseBrightness(other.getIncreaseBrightness());
      }
      if (other.getDecreaseBrightness() != false) {
        setDecreaseBrightness(other.getDecreaseBrightness());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ncirl.smartwarehouse.LightResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ncirl.smartwarehouse.LightResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean increaseBrightness_ ;
    /**
     * <code>bool increaseBrightness = 1;</code>
     */
    public boolean getIncreaseBrightness() {
      return increaseBrightness_;
    }
    /**
     * <code>bool increaseBrightness = 1;</code>
     */
    public Builder setIncreaseBrightness(boolean value) {
      
      increaseBrightness_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool increaseBrightness = 1;</code>
     */
    public Builder clearIncreaseBrightness() {
      
      increaseBrightness_ = false;
      onChanged();
      return this;
    }

    private boolean decreaseBrightness_ ;
    /**
     * <code>bool decreaseBrightness = 2;</code>
     */
    public boolean getDecreaseBrightness() {
      return decreaseBrightness_;
    }
    /**
     * <code>bool decreaseBrightness = 2;</code>
     */
    public Builder setDecreaseBrightness(boolean value) {
      
      decreaseBrightness_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool decreaseBrightness = 2;</code>
     */
    public Builder clearDecreaseBrightness() {
      
      decreaseBrightness_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ncirl.smartwarehouse.LightResponse)
  }

  // @@protoc_insertion_point(class_scope:com.ncirl.smartwarehouse.LightResponse)
  private static final com.ncirl.smartwarehouse.LightResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ncirl.smartwarehouse.LightResponse();
  }

  public static com.ncirl.smartwarehouse.LightResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LightResponse>
      PARSER = new com.google.protobuf.AbstractParser<LightResponse>() {
    @java.lang.Override
    public LightResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LightResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LightResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LightResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ncirl.smartwarehouse.LightResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

