// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightSensorService.proto

package com.ncirl.smartwarehouse;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.smartwarehouse.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool increaseBrightness = 1;</code>
   */
  boolean getIncreaseBrightness();

  /**
   * <code>bool decreaseBrightness = 2;</code>
   */
  boolean getDecreaseBrightness();
}
