// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightSensorService.proto

package com.ncirl.smartwarehouse;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.smartwarehouse.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 luminousIntensity = 1;</code>
   */
  int getLuminousIntensity();
}
