// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotionSensorService.proto

package com.ncirl.smartwarehouse;

public final class MotionSensorServiceProto {
  private MotionSensorServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_smartwarehouse_DetectMotionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_smartwarehouse_DetectMotionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031MotionSensorService.proto\022\030com.ncirl.s" +
      "martwarehouse\"5\n\031DetectMotionStatusReque" +
      "st\022\030\n\020isMotionDetected\030\001 \001(\010\"\'\n\024DetectMo" +
      "tionResponse\022\017\n\007message\030\001 \001(\t2\214\001\n\023Motion" +
      "SensorService\022u\n\014detectMotion\0223.com.ncir" +
      "l.smartwarehouse.DetectMotionStatusReque" +
      "st\032..com.ncirl.smartwarehouse.DetectMoti" +
      "onResponse(\001B6\n\030com.ncirl.smartwarehouse" +
      "B\030MotionSensorServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_smartwarehouse_DetectMotionStatusRequest_descriptor,
        new java.lang.String[] { "IsMotionDetected", });
    internal_static_com_ncirl_smartwarehouse_DetectMotionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ncirl_smartwarehouse_DetectMotionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_smartwarehouse_DetectMotionResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
