// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatService.proto

package com.ncirl.smartwarehouse;

public interface ThermostatReadingInformationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.smartwarehouse.ThermostatReadingInformation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string temperature = 1;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 1;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();
}
