// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThermostatService.proto

package com.ncirl.smartwarehouse;

public final class ThermostatServiceProto {
  private ThermostatServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_smartwarehouse_RequestSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_smartwarehouse_RequestSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_smartwarehouse_ThermostatReadingInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_smartwarehouse_ThermostatReadingInformation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ThermostatService.proto\022\030com.ncirl.sma" +
      "rtwarehouse\" \n\rRequestSource\022\017\n\007request\030" +
      "\001 \001(\t\"3\n\034ThermostatReadingInformation\022\023\n" +
      "\013temperature\030\001 \001(\0012\222\002\n\021ThermostatService" +
      "\022~\n\033getCurrentThermostatReading\022\'.com.nc" +
      "irl.smartwarehouse.RequestSource\0326.com.n" +
      "cirl.smartwarehouse.ThermostatReadingInf" +
      "ormation\022}\n\030streamThermostatReadings\022\'.c" +
      "om.ncirl.smartwarehouse.RequestSource\0326." +
      "com.ncirl.smartwarehouse.ThermostatReadi" +
      "ngInformation0\001B4\n\030com.ncirl.smartwareho" +
      "useB\026ThermostatServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ncirl_smartwarehouse_RequestSource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ncirl_smartwarehouse_RequestSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_smartwarehouse_RequestSource_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_com_ncirl_smartwarehouse_ThermostatReadingInformation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ncirl_smartwarehouse_ThermostatReadingInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_smartwarehouse_ThermostatReadingInformation_descriptor,
        new java.lang.String[] { "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
